baseURL = "https://antonyflores88.github.io/my-lab-blog/"
languageCode = "en-us"
title = "Tony Cloud Journey"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  showReadingTime = true
  mainSections = []
  customCSS = ["css/custom.css"]


[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 3

[markup.goldmark.renderer]
  unsafe = true
